/* mysharedlibrary.h generated by valac 0.36.8, the Vala compiler, do not modify */


#ifndef __MYSHAREDLIBRARY_H__
#define __MYSHAREDLIBRARY_H__

#include <glib.h>

G_BEGIN_DECLS



gint mysharedlibrary_sum (gint a, gint b);
gint mysharedlibrary_square (gint a);


G_END_DECLS

#endif
