/* MySharedLibrary.vapi generated by valac 0.36.8, do not modify. */

namespace Mysharedlibrary {
	[CCode (cheader_filename = "mysharedlibrary.h")]
	public static int square (int a);
	[CCode (cheader_filename = "mysharedlibrary.h")]
	public static int sum (int a, int b);
}
